export type ExerciseCatalogMetadata = {
  global: boolean;
};

export type ExerciseCatalogSeedItem = {
  id: string;
  name: string;
  equipment: "Barbell" | "Cable" | "Dumbbell" | "Machine";
  muscle: string;
  primaryMuscles: string[];
  secondaryMuscles: string[];
  metadata: ExerciseCatalogMetadata;
};

export const EXERCISE_EQUIPMENT_OPTIONS = [
  "Barbell",
  "Cable",
  "Dumbbell",
  "Bodyweight",
  "Machine",
  "Other",
] as const;

export const MUSCLE_GROUP_OPTIONS = [
  "Chest",
  "Shoulders",
  "Upper Back",
  "Lats",
  "Lower Back",
  "Quads",
  "Hamstrings",
  "Glutes",
  "Calves",
  "Biceps",
  "Triceps",
  "Forearms",
  "Upper Abs",
  "Lower Abs",
  "Obliques",
] as const;

const globalMetadata: ExerciseCatalogMetadata = {
  global: true,
};

function createExercise(
  id: string,
  name: string,
  equipment: ExerciseCatalogSeedItem["equipment"],
  muscle: string,
  primaryMuscles: string[],
  secondaryMuscles: string[],
): ExerciseCatalogSeedItem {
  return {
    id,
    name,
    equipment,
    muscle,
    primaryMuscles,
    secondaryMuscles,
    metadata: globalMetadata,
  };
}

export const GLOBAL_EXERCISE_CATALOG: ExerciseCatalogSeedItem[] = [
  createExercise(
    "bench-press-barbell",
    "Bench Press",
    "Barbell",
    "Chest",
    ["Chest"],
    ["Shoulders", "Triceps"],
  ),
  createExercise(
    "incline-bench-press-barbell",
    "Incline Bench Press",
    "Barbell",
    "Chest",
    ["Chest"],
    ["Shoulders", "Triceps"],
  ),
  createExercise(
    "bent-over-row-barbell",
    "Bent Over Row",
    "Barbell",
    "Upper Back",
    ["Upper Back", "Lats"],
    ["Biceps", "Forearms", "Lower Back"],
  ),
  createExercise(
    "shoulder-press-barbell",
    "Shoulder Press",
    "Barbell",
    "Shoulders",
    ["Shoulders"],
    ["Triceps", "Chest"],
  ),
  createExercise(
    "squat-barbell",
    "Squat",
    "Barbell",
    "Quads",
    ["Quads"],
    ["Glutes", "Hamstrings", "Calves"],
  ),
  createExercise(
    "front-squat-barbell",
    "Front Squat",
    "Barbell",
    "Quads",
    ["Quads"],
    ["Glutes", "Hamstrings", "Calves"],
  ),
  createExercise(
    "deadlift-barbell",
    "Deadlift",
    "Barbell",
    "Glutes",
    ["Glutes"],
    ["Hamstrings", "Quads", "Upper Back", "Lower Back", "Forearms"],
  ),
  createExercise(
    "romanian-deadlift-barbell",
    "Romanian Deadlift",
    "Barbell",
    "Hamstrings",
    ["Hamstrings"],
    ["Glutes", "Lower Back", "Forearms"],
  ),
  createExercise(
    "hip-thrust-barbell",
    "Hip Thrust",
    "Barbell",
    "Glutes",
    ["Glutes"],
    ["Hamstrings", "Quads"],
  ),
  createExercise(
    "bicep-curl-barbell",
    "Bicep Curl",
    "Barbell",
    "Biceps",
    ["Biceps"],
    ["Forearms"],
  ),
  createExercise(
    "ez-bar-preacher-curl-barbell",
    "EZ Bar Preacher Curl",
    "Barbell",
    "Biceps",
    ["Biceps"],
    ["Forearms"],
  ),
  createExercise(
    "lying-tricep-extension-barbell",
    "Lying Tricep Extension",
    "Barbell",
    "Triceps",
    ["Triceps"],
    ["Shoulders"],
  ),

  createExercise(
    "bench-press-dumbbell",
    "Bench Press",
    "Dumbbell",
    "Chest",
    ["Chest"],
    ["Shoulders", "Triceps"],
  ),
  createExercise(
    "incline-bench-press-dumbbell",
    "Incline Bench Press",
    "Dumbbell",
    "Chest",
    ["Chest"],
    ["Shoulders", "Triceps"],
  ),
  createExercise(
    "bent-over-row-dumbbell",
    "Bent Over Row",
    "Dumbbell",
    "Upper Back",
    ["Upper Back", "Lats"],
    ["Biceps", "Forearms", "Lower Back"],
  ),
  createExercise(
    "shoulder-press-dumbbell",
    "Shoulder Press",
    "Dumbbell",
    "Shoulders",
    ["Shoulders"],
    ["Triceps", "Chest"],
  ),
  createExercise(
    "lateral-raise-dumbbell",
    "Lateral Raise",
    "Dumbbell",
    "Shoulders",
    ["Shoulders"],
    ["Upper Back"],
  ),
  createExercise(
    "rear-delt-fly-dumbbell",
    "Rear Delt Fly",
    "Dumbbell",
    "Shoulders",
    ["Shoulders"],
    ["Upper Back"],
  ),
  createExercise(
    "bicep-curl-dumbbell",
    "Bicep Curl",
    "Dumbbell",
    "Biceps",
    ["Biceps"],
    ["Forearms"],
  ),
  createExercise(
    "hammer-curl-dumbbell",
    "Hammer Curl",
    "Dumbbell",
    "Forearms",
    ["Forearms"],
    ["Biceps"],
  ),
  createExercise(
    "squat-dumbbell",
    "Squat",
    "Dumbbell",
    "Quads",
    ["Quads"],
    ["Glutes", "Hamstrings", "Calves"],
  ),
  createExercise(
    "romanian-deadlift-dumbbell",
    "Romanian Deadlift",
    "Dumbbell",
    "Hamstrings",
    ["Hamstrings"],
    ["Glutes", "Lower Back", "Forearms"],
  ),
  createExercise(
    "pullover-dumbbell",
    "Pullover",
    "Dumbbell",
    "Lats",
    ["Lats", "Chest"],
    ["Triceps", "Shoulders"],
  ),

  createExercise(
    "lat-pulldown-cable",
    "Lat Pulldown",
    "Cable",
    "Lats",
    ["Lats"],
    ["Upper Back", "Biceps", "Forearms"],
  ),
  createExercise(
    "parallel-grip-lat-pulldown-cable",
    "Parallel Grip Lat Pulldown",
    "Cable",
    "Lats",
    ["Lats"],
    ["Upper Back", "Biceps", "Forearms"],
  ),
  createExercise(
    "seated-cable-row-v-grip",
    "Seated Cable Row - V Grip",
    "Cable",
    "Upper Back",
    ["Upper Back", "Lats"],
    ["Biceps", "Forearms", "Lower Back"],
  ),
  createExercise(
    "cable-standing-fly",
    "Standing Fly",
    "Cable",
    "Chest",
    ["Chest"],
    ["Shoulders"],
  ),
  createExercise(
    "shoulder-press-cable",
    "Shoulder Press",
    "Cable",
    "Shoulders",
    ["Shoulders"],
    ["Triceps", "Chest"],
  ),
  createExercise(
    "lateral-raise-cable",
    "Lateral Raise",
    "Cable",
    "Shoulders",
    ["Shoulders"],
    ["Upper Back"],
  ),
  createExercise(
    "tricep-pushdown-cable",
    "Tricep Pushdown",
    "Cable",
    "Triceps",
    ["Triceps"],
    [],
  ),
  createExercise(
    "tricep-extension-cable",
    "Overhead Tricep Extension",
    "Cable",
    "Triceps",
    ["Triceps"],
    ["Shoulders"],
  ),
  createExercise(
    "cable-curl",
    "Cable Curl",
    "Cable",
    "Biceps",
    ["Biceps"],
    ["Forearms"],
  ),
  createExercise(
    "rope-hammer-curl-cable",
    "Rope Hammer Curl",
    "Cable",
    "Forearms",
    ["Forearms"],
    ["Biceps"],
  ),

  createExercise(
    "chest-press-machine",
    "Chest Press",
    "Machine",
    "Chest",
    ["Chest"],
    ["Shoulders", "Triceps"],
  ),
  createExercise(
    "incline-chest-press-machine",
    "Incline Chest Press",
    "Machine",
    "Chest",
    ["Chest"],
    ["Shoulders", "Triceps"],
  ),
  createExercise(
    "pec-deck-machine",
    "Pec Deck",
    "Machine",
    "Chest",
    ["Chest"],
    ["Shoulders"],
  ),
  createExercise(
    "assisted-chest-dip-machine",
    "Assisted Chest Dip",
    "Machine",
    "Chest",
    ["Chest"],
    ["Shoulders", "Triceps", "Lats"],
  ),
  createExercise(
    "assisted-tricep-dip-machine",
    "Assisted Tricep Dip",
    "Machine",
    "Triceps",
    ["Triceps"],
    ["Chest", "Shoulders"],
  ),
  createExercise(
    "shoulder-press-machine",
    "Shoulder Press",
    "Machine",
    "Shoulders",
    ["Shoulders"],
    ["Triceps", "Chest"],
  ),
  createExercise(
    "lateral-raise-machine",
    "Lateral Raise",
    "Machine",
    "Shoulders",
    ["Shoulders"],
    ["Upper Back"],
  ),
  createExercise(
    "reverse-fly-machine",
    "Reverse Fly",
    "Machine",
    "Shoulders",
    ["Shoulders"],
    ["Upper Back"],
  ),
  createExercise(
    "lat-pulldown-machine",
    "Lat Pulldown",
    "Machine",
    "Lats",
    ["Lats"],
    ["Upper Back", "Biceps", "Forearms"],
  ),
  createExercise(
    "high-row-machine",
    "High Row",
    "Machine",
    "Upper Back",
    ["Upper Back", "Lats"],
    ["Biceps", "Forearms"],
  ),
  createExercise(
    "iso-lateral-high-row-machine",
    "Iso Lateral High Row",
    "Machine",
    "Upper Back",
    ["Upper Back", "Lats"],
    ["Biceps", "Forearms"],
  ),
  createExercise(
    "seated-row-machine",
    "Seated Row",
    "Machine",
    "Upper Back",
    ["Upper Back", "Lats"],
    ["Biceps", "Forearms", "Lower Back"],
  ),
  createExercise(
    "assisted-pull-up-machine",
    "Assisted Pull Up",
    "Machine",
    "Lats",
    ["Lats"],
    ["Upper Back", "Biceps", "Forearms"],
  ),
  createExercise(
    "back-extension-machine",
    "Back Extension",
    "Machine",
    "Lower Back",
    ["Lower Back"],
    ["Glutes", "Hamstrings"],
  ),
  createExercise(
    "leg-press-machine",
    "Leg Press",
    "Machine",
    "Quads",
    ["Quads"],
    ["Glutes", "Hamstrings", "Calves"],
  ),
  createExercise(
    "hack-squat-machine",
    "Hack Squat",
    "Machine",
    "Quads",
    ["Quads"],
    ["Glutes", "Hamstrings", "Calves"],
  ),
  createExercise(
    "quad-extension-machine",
    "Quad Extension",
    "Machine",
    "Quads",
    ["Quads"],
    [],
  ),
  createExercise(
    "leg-extension-machine",
    "Leg Extension",
    "Machine",
    "Quads",
    ["Quads"],
    [],
  ),
  createExercise(
    "seated-leg-curl-machine",
    "Seated Leg Curl",
    "Machine",
    "Hamstrings",
    ["Hamstrings"],
    ["Calves"],
  ),
  createExercise(
    "lying-leg-curl-machine",
    "Lying Leg Curl",
    "Machine",
    "Hamstrings",
    ["Hamstrings"],
    ["Calves"],
  ),
  createExercise(
    "glute-drive-machine",
    "Glute Drive",
    "Machine",
    "Glutes",
    ["Glutes"],
    ["Hamstrings", "Quads"],
  ),
  createExercise(
    "standing-calf-raise-machine",
    "Standing Calf Raise",
    "Machine",
    "Calves",
    ["Calves"],
    [],
  ),
  createExercise(
    "hack-squat-standing-calf-raise-machine",
    "Hack Squat Standing Calf Raise",
    "Machine",
    "Calves",
    ["Calves"],
    [],
  ),
  createExercise(
    "seated-calf-raise-machine",
    "Seated Calf Raise",
    "Machine",
    "Calves",
    ["Calves"],
    [],
  ),
  createExercise(
    "preacher-curl-machine",
    "Preacher Curl",
    "Machine",
    "Biceps",
    ["Biceps"],
    ["Forearms"],
  ),
  createExercise(
    "bicep-curl-machine",
    "Bicep Curl",
    "Machine",
    "Biceps",
    ["Biceps"],
    ["Forearms"],
  ),
  createExercise(
    "dip-machine",
    "Dip",
    "Machine",
    "Triceps",
    ["Triceps"],
    ["Chest", "Shoulders"],
  ),
  createExercise(
    "tricep-extension-machine",
    "Tricep Extension",
    "Machine",
    "Triceps",
    ["Triceps"],
    [],
  ),
  createExercise(
    "wrist-curl-machine",
    "Wrist Curl",
    "Machine",
    "Forearms",
    ["Forearms"],
    [],
  ),
  createExercise(
    "reverse-wrist-curl-machine",
    "Reverse Wrist Curl",
    "Machine",
    "Forearms",
    ["Forearms"],
    [],
  ),
  createExercise(
    "ab-crunch-machine",
    "Ab Crunch",
    "Machine",
    "Upper Abs",
    ["Upper Abs"],
    ["Obliques"],
  ),
  createExercise(
    "leg-raise-crunch-machine",
    "Leg Raise Crunch",
    "Machine",
    "Lower Abs",
    ["Lower Abs"],
    ["Upper Abs", "Obliques"],
  ),
  createExercise(
    "rotary-torso-machine",
    "Rotary Torso",
    "Machine",
    "Obliques",
    ["Obliques"],
    ["Upper Abs", "Lower Abs"],
  ),
];
